{% set version = "2.1.0" %}

package:
  name: noteslib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/noteslib/noteslib-{{ version }}.tar.gz
  sha256: ca2a4de4a6982785a0160f96085fbc83630fdf0a1f8ed5a9c88a4dd5c3e93ca6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [unix or py2k]

requirements:
  host:
    - python
    - pip
    - flit
    - pywin32
  run:
    - python
    - pywin32

test:
  imports:
    - noteslib

about:
  home: https://pypi.org/project/noteslib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python classes for manipulating Lotus Notes/Domino objects via COM"
  doc_url: https://pypi.org/project/noteslib

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - mwilson8
